### PR TITLE
Bdtdevel

### PR DESCRIPTION
**Pull request by vischia**

### CODE REVIEW

**Comment by vischia** [comment]
Fixed trainings for low mass: rocs are here: https://vischia.web.cern.ch/vischia/chhiggs13TeV/rocstest/

**Comment by vischia** [comment]
(medium+high I am retraining them again)

**Comment by vischia** [comment]
With the jet multipliciy variables (questionable choice), the dedicated low-mass trainings perform worse than the combined low mass one: probably this is due to the structures, hinting to a proto-multiclass behaviour:
(ROCS are in 1Mass, 2Mass, and 3Mass of: https://vischia.web.cern.ch/vischia/chhiggs13TeV/rocstest/ )

The rest of the points are still training.

After finishing with the DNN approach that I am looking to in these days, I will probably look into a full-fledged multiclass discriminant, once I clear out the doubts on the different bjet content and the variables.

**Comment by mariadalfonso** [comment]
aux/tb_trainings/tb_1l_4Mass_vsall_SR_BDT.weights.xml contains the ncentral and nbjets
should be renamed as aux/tb_trainings/tb_1l_4Mass_vsall_SRCR_BDT.weights.xml

**Comment by vischia** [comment]
Uh, dammit, I missed it.

Will do now while committing the rest

**Comment by vischia** [comment]
(later I will reupload the 4 SR-only, that got rewritten

**Pull request merged**
