### PR TITLE
SRCR trainings for 2L

### PR DESCRIPTION
**Pull request by vischia**
Hi,
here are the trainings!

I have to configure the ROC script for the 2L, will do that half-morning while changing flights and upload to the usual link!

I have also some additional result I have prepared (DNN and optimized BDT) I am finishing tests on that.

Cheers,
Pietro

### CODE REVIEW

**Comment by vischia** [comment]
P.S.
I see you have some keras stuff in the repository, so I will assume you can import an HDF5 Keras model without too much overhead.

**Comment by mariadalfonso** [comment]
@vischia 
in the 2L we still miss the lepton Asymmetry, 
We need to have at least the lep1_pt

For the 2016 analysis I still hope to finalize the 2D binning (Haevy flavour vs light flavour). If you have some update on that I can recheck in time for the workshop.

Will be good to mention the fancy MVA technologies (DNN,BDT, keras, TensorFlow and any other on the market) only in view of the 2017 analysis.

**Comment by mariadalfonso** [comment]
@vischia 
aux/tb_trainings/tb_2l_6Mass_vsall_SRCR_BDT.weights.xml and also the 5,4,3,2,1
have only the njets and nbjets and none of the other variables

**Comment by mariadalfonso** [comment]
@vischia here the roc curves for the 2L 
http://dalfonso.web.cern.ch/dalfonso/ChargedHiggsTB/OCT15/?match=_2L
there is no discrimination at low mass.
Can you add the lepCharge asymmetry ?

**Comment by vischia** [comment]
Hi,

uh, I see, the lep2_pt was missing from my skimmed trees, so my checks on the existence of the variables excluded it from being added as training variables. I now added it and am already retraining with the asymmetry included. Tomorrow morning they will be ready.

Sure, I will give another look at the 2D binning as soon as I am done comparing ROCs for the deep network for 2016 data (not waiting 2017 on that), and for an improved 1D BDT I have been testing these days.

**Comment by vischia** [comment]
Hi,
I uploaded the first updated training (i.e. with lepton asymmetry). 
Before I go to sleep I'll upload whatever is ready at that time, and tomorrow morning the rest.

**Comment by vischia** [comment]
(low mass trainings now have all variables --> fixed)

**Comment by vischia** [comment]
Hi, can you please merge, so that I can open another one with other sets of stuff?

Cheers,
Pietro

**Pull request merged**
