### PR TITLE
First Keras model  (still tuning stuff), with some ROC improvement w.…

### PR DESCRIPTION
**Pull request by vischia**
Some improvement w.r.t. BDT, except at the two extremes, where it is washed out (see table below)

For the moment it uses green set, without jet multiplicity.

I am finishing training a similar model with lower-level info, that should on paper result in improved results with respect to this one.

I am still tuning the parametric model, but please already take a look at the limits to see what happens there (very curious)

Full ROC curves in https://vischia.web.cern.ch/vischia/chhiggs13TeV/rocs_dnn/
The discriminator is defined between 0 and 1 (best range)

This is the full already-trained model, it's just a matter of loading it and applying it.
The set of training events is the same as the BDTs.

SinglePoint-BDT    Combined-BDT     DNN                                                                                            
                                                                                                                                  
1mass: 66.8485   73.6166     72.76                                                                                                 
2mass: 70.3794   73.6166     75.11                                                                                                 
3mass: 73.0254   73.6166     74.52                                                                                                 
4mass: 74.9284   73.6166     74.30                                                                                                 
5mass: 73.7455   73.6166     74.69                                                                                                 
6mass: 75.5426   73.6166     76.20                                                                                                 
7mass:    -      78.54       80.33                                                                                                 
8mass:    -         -          -                                                                                                   
9mass:    -      78.54       82.76                                                                                                 
10mass:   -         -          -                                                                                                   
11mass: 87.5355  92.4834     91.60                                                                                                 
12mass: 93.2719  92.4834     93.93                                                                                                 
13mass: 97.9472  92.4834     98.70                                                                                                 
14mass: 99.0661  92.4834     99.39

### CODE REVIEW

**Comment by vischia** [comment]
Hi, I have uploaded an updated trained model, providing a 10% improvement at low mass, and decreasing to 1% at 2 TeV. It loses less than onepercent at 3 TeV, I will work to improve that behaviour.

(DNN1 is the upoad from yesterday, DNN5 is this upload. The intermediate ones are not worth uploading.)
SinglePoint-BDT    Combined-BDT        DNN1        DNN5                         
                                                                                                         
1mass: 66.8485   73.6166     72.76         81.05                       
2mass: 70.3794   73.6166     75.11         81.21                       
3mass: 73.0254   73.6166     74.52         85.22                       
4mass: 74.9284   73.6166     74.30         84.02                       
5mass: 73.7455   73.6166     74.69         83.91                       
6mass: 75.5426   73.6166     76.20         84.18                       
7mass:    -            78.54         80.33         86.32                       
8mass:    -                 -                 -             -                    
9mass:    -            78.54         82.76         87.24                       
10mass:   -                -                 -             -                            
11mass: 87.5355  92.4834     91.60         93.35                       
12mass: 93.2719  92.4834     93.93         94.81                       
13mass: 97.9472  92.4834     98.70         98.47                       
14mass: 99.0661  92.4834     99.39         98.99

**Comment by vischia** [comment]
On deeper investigation, probably you prefer a LWTNN C++ class instead of the trained model?

Is it easier for you to integrate this?

**Comment by vischia** [comment]
BDT 2D 1l low mass for consistency check (will run the binning procedure tomorrow morning together with all the rest).

I will probably have an updated file for DNN tomorrow or saturday, can you please also confirm if you prefer a LWTNN C++ class? I see @amarini had requested a review for this to @mariadalfonso , but the review is still pending. 

Cheers,
Pietro

**Comment by vischia** [comment]
(BTW, I am running also the split masses for the 2D, but I have low hopes because of the statistic split by flavour)

**Comment by vischia** [comment]
Ping! Do you see any issue in the format/variables/something or can I push the rest of the trainings? What about LWTNN, is that OK as a format.

**Comment by mariadalfonso** [comment]
regarding the file I see in #0f9f6d9 the name report "SR" for comparison with the 1D we need the extended SR/CR.
You can add the other mass training and the updated binning files.

**Comment by vischia** [comment]
Ah, this is the extended, I had just not updated the labels for the 2D. I will recommit with updated labels, but the trainings themselves are already SRCR

**Comment by mariadalfonso** [comment]
@vischia 

For the 2D I see committed only the 
aux/tb_trainings/tb_1l_lowMass_vslf_SR_BDT.weights.xml
aux/tb_trainings/tb_1l_lowMass_vshf_SR_BDT.weights.xml
Do I need to update the binning file aux/binning_1l_lowmass_2l.root ? 
how many bins you expect to have ? before was 6.

in case the medium/high are ready I can also run these at the same time.

**Comment by vischia** [comment]
2D:

lowmass: 1bin
1mass: 2 bins
2mass: 3 bins
3mass: 4 bins
4mass: 1 bin
5mass: 2 bins
6mass: 3 bins

However they have a weird behaviour, as it seems they are sending all events in the same place, so I need to rerun them one by one and check what is happening.

**Pull request merged**
