### PR TITLE
New 2L training

### PR DESCRIPTION
**Pull request by vischia**

### CODE REVIEW

**Comment by mariadalfonso** [comment]
@vischia 
What is exactly this ? 
the variables choice/order is as in https://github.com/MiT-HEP/ChargedHiggs/pull/187 ?
there was supposed to be the 1l also ?
Naming convention is hard now

**Comment by vischia** [comment]
Hi,

The 2L, same naming convention, to re
place the latest one!

1L at the moment keep the current one

Pietro

El 4 dic. 2017 14:10, "mariadalfonso" <notifications@github.com> escribió:

@vischia <https://github.com/vischia>
What is exactly this ?
the variables choice/order is as in #187
<https://github.com/MiT-HEP/ChargedHiggs/pull/187> ?
there was supposed to be the 1l also ?
Naming convention is hard now

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MiT-HEP/ChargedHiggs/pull/188#issuecomment-348957778>,
or mute the thread

**Comment by mariadalfonso** [comment]
@vischia not clear is V1 or V2 ?
V1 https://github.com/MiT-HEP/ChargedHiggs/pull/186
V2 https://github.com/MiT-HEP/ChargedHiggs/pull/187

v1
'bjet_pt[0]', 'ht', 'DRl1b1', 'DEtaMaxBB', 'DRbbmin', 'MassMinlb', 'AvCSVPt', 'FW2', 'Cen', 'DRlbmin', 'AvDRBB', 'DRlbmaxPT', 'mtMin', '(lep1_pt-lep2_pt)/(lep1_pt+lep2_pt)', 'NcentralJets', 'NBJets'

v2:
'bjet_pt[0]', 'ht', 'DRl1b1', 'DEtaMaxBB', 'DRbbmin', 'MassMinlb', 'AvCSVPt', 'FW2', 'Cen', 'met_pt', 'lep1_pt', 'DRlbmaxPT', 'lep2_pt', 'mtMin', '(lep1_pt-lep2_pt)/(lep1_pt+lep2_pt)', 'NcentralJets', 'NBJets'

**Comment by vischia** [comment]
Hi,

The latest one, V2 :)

El 4 dic. 2017 14:24, "mariadalfonso" <notifications@github.com> escribió:

@vischia <https://github.com/vischia> not clear is V1 or V2 ?
V1 #186 <https://github.com/MiT-HEP/ChargedHiggs/pull/186>
V2 #187 <https://github.com/MiT-HEP/ChargedHiggs/pull/187>

v1
'bjet_pt[0]', 'ht', 'DRl1b1', 'DEtaMaxBB', 'DRbbmin', 'MassMinlb',
'AvCSVPt', 'FW2', 'Cen', 'DRlbmin', 'AvDRBB', 'DRlbmaxPT', 'mtMin',
'(lep1_pt-lep2_pt)/(lep1_pt+lep2_pt)', 'NcentralJets', 'NBJets'

v2:
'bjet_pt[0]', 'ht', 'DRl1b1', 'DEtaMaxBB', 'DRbbmin', 'MassMinlb',
'AvCSVPt', 'FW2', 'Cen', 'met_pt', 'lep1_pt', 'DRlbmaxPT', 'lep2_pt',
'mtMin', '(lep1_pt-lep2_pt)/(lep1_pt+lep2_pt)', 'NcentralJets', 'NBJets'

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MiT-HEP/ChargedHiggs/pull/188#issuecomment-348960906>,
or mute the thread

**Comment by mariadalfonso** [comment]
perfect, 
I will re-run now

**Pull request closed without merging**
