### PR TITLE
Individual training for 2TeV

### PR DESCRIPTION
**Pull request by vischia**
Will update as soon as the files are ready

(3 TeV most likely tomorrow morning. Perhaps the 1L will be ready before I go to sleep, not guaranteed though)

### CODE REVIEW

**Comment by vischia** [comment]
Added:

a) file containing the number of events per each region (low, medium, high) and for each mass point I am plugging in from the tree (JUN6) to the machinery

b) script that easily computes the number of signal events used for the training for each of the dump files that are in the aux/ and in the two subsets of the aux. That number is supposed be 1/3 of the corresponding number from the file mentioned in a)

**Comment by vischia** [comment]
The script in b) is run as "aux/trainingEventsCounter.sh"

**Comment by vischia** [comment]
I am having bad connection in OVD airport, will try again to commit in Madrid in a few hours ;)

**Comment by vischia** [comment]
Finally ssh decided to work ;) 3TeV-2L uploaded

**Comment by vischia** [comment]
Hi,

here are the 3 TeV complete files (the 2L had an issue in the selection that is now fixed).

I launched the procedure for the 10-11 and for the 12, but it did not finish running, and from now to next Tuesday I won't have the laptop with me, so those will have to wait :(


Cheers,
Pietro

**Comment by vischia** [comment]
Done, you can merge!

**Comment by vischia** [comment]
("11" is labeled only "11" because "10" is empty)

**Comment by mariadalfonso** [comment]
Is it possible to update the lep_category also for the 
aux/tb_*l_lowMass_vsall_BDT.dump.txt
aux/tb_*l_mediumMass_vsall_BDT.dump.txt

so that I have the full clean set

**Comment by vischia** [comment]
Ah sure !

Tomorrow!

**Pull request merged**
